### ISSUE TITLE
Error in error handling code for new atf

### ISSUE THREAD

**Issue by larsgw** [cdli-gh/jtf-lib#6]
I am getting an error when I input this ATF in uqnu, or attempt to parse it through the jtf-lib API.

```
&P298489 = CBCY 03, p. 208, NBC
@seal
1. ha-ba-lu5-ge2
2. ensi2 Adab{ki}
3. ur-pa4-mu-ra
4. dub-sar
5. ARAD2-zu
```

The error seems to originate from code that handles syntax errors.

```
TypeError: Cannot read property '1' of null
    at nearlyError2Object (/var/app/src/ATFParser/parserTools.js:118:23)
    at processError (/var/app/src/ATFParser/parserTools.js:91:10)
    at parse (/var/app/src/ATFParser/parserTools.js:23:17)
    at ATF2JTF (/var/app/src/Converters/ATF2JTF.js:41:13)
    at /var/app/src/routes/routes.js:56:17
    at Layer.handle [as handle_request] (/var/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/app/node_modules/express/lib/router/layer.js:95:5)
    at /var/app/node_modules/express/lib/router/index.js:281:22
```

**Comment by epageperron** [comment]
@Vishv07 is there any chance you could look into this?

**Comment by epageperron** [comment]
@darth-cheney did your PR fix this?

**Comment by darth-cheney** [comment]
I believe so. Running the following short script no longer throws any error:
```javascript
const lib = require("./src/index.js");
let atf = `&P298489 = CBCY 03, p. 208, NBC
@seal
1. ha-ba-lu5-ge2
2. ensi2 Adab{ki}
3. ur-pa4-mu-ra
4. dub-sar
5. ARAD2-zu`;

lib.ATF2JTF(atf);
```

**Comment by epageperron** [comment]
great thanks :)
